  version: '3.8'

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        DATASOURCE_URL: "${DATASOURCE_URL}"
        DATASOURCE_USERNAME: "${DATASOURCE_USERNAME}"
        DATASOURCE_PASSWORD: "${DATASOURCE_PASSWORD}"
      env_file:
        - .env     # Datei, um Umgebungsvariablen zu definierena